// Standalone reusable FTC Android library.
plugins {
    id 'maven-publish'
}

apply plugin: 'com.android.library'

android {
    namespace = 'org.firstinspires.ftc.generalUtilities'
    compileSdkVersion 34

    defaultConfig {
        minSdkVersion 24
        //noinspection ExpiredTargetSdkVersion
        targetSdkVersion 28
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    buildFeatures {
        buildConfig = false
    }

    publishing {
        singleVariant('release') {
            withSourcesJar()
            withJavadocJar()
        }
    }
}

repositories {
    mavenCentral()
    maven { url "https://jitpack.io" }
    google()
}

dependencies {
    api project(':GeneralUtilities')

    implementation 'org.firstinspires.ftc:Inspection:11.0.0'
    implementation 'org.firstinspires.ftc:Blocks:11.0.0'
    implementation 'org.firstinspires.ftc:RobotCore:11.0.0'
    implementation 'org.firstinspires.ftc:RobotServer:11.0.0'
    implementation 'org.firstinspires.ftc:OnBotJava:11.0.0'
    implementation 'org.firstinspires.ftc:Hardware:11.0.0'
    implementation 'org.firstinspires.ftc:FtcCommon:11.0.0'
    implementation 'org.firstinspires.ftc:Vision:11.0.0'
    implementation 'androidx.appcompat:appcompat:1.2.0'
}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                from components.release
                groupId = 'com.github.FIRST-4030'
                artifactId = 'GeneralUtilitiesLibrary'
                version = '1.0.3'
            }
        }
    }
}
